### PR TITLE
Add script for automating creation of issues and merge requests for Ironbank images

### PR DESCRIPTION
**Pull request by lucasrod16**
Let me know what you think!

### CODE REVIEW

**Comment by corang** [comment]
I like it! Did you want to generify it before committing it to main?

**Review by runyontr — APPROVED** [review]
Looks great!  This looks like it works well for RapidFort.  In the future, if this is helpful for other, we could try and abstract away and discover the images/git repos/etc when the script is run inside the repo.

Thanks for doing this Lucas!

**Comment by lucasrod16** [comment]
> I like it! Did you want to generify it before committing it to main?

I think it would be great for it to be more generic. I'm not sure how to easily accomplish that. Are there things we can do with this script to accomplish that?

**Comment by lucasrod16** [comment]
> Looks great! This looks like it works well for RapidFort. In the future, if this is helpful for other, we could try and abstract away and discover the images/git repos/etc when the script is run inside the repo.

That's a great idea.

**Pull request merged**
